# https://rubocop.readthedocs.io/en/latest/

# I always use double quotes
Style/StringLiterals:
  EnforcedStyle: double_quotes

# Well, it's seem it's a rails project
Rails:
  Enabled: true
Layout/IndentationConsistency:
  EnforcedStyle: rails
AllCops:
  Exclude:
    - db/schema.rb
    - bin/setup     # https://github.com/rubocop-hq/rubocop-rails/issues/13
    - bin/update    # https://github.com/rubocop-hq/rubocop-rails/issues/13
